### ISSUE TITLE
pctg

### ISSUE THREAD

**Issue by mrjcleaver** [dinever/DiskUsage--bersicht#1]
... it's not completely obvious that this means percentage. (Got me Googling!)

How about just writing "FULL" ?

![monosnap 2016-03-04 06-23-34](https://cloud.githubusercontent.com/assets/59202/13525824/b8b854cc-e1d1-11e5-999b-ead9b27f50f8.png)

Thanks!

**Comment by dinever** [comment]
Hi @mrjcleaver,

Sorry for this late reply, I have just changed it to `FULL`. Thank you for you suggestion! :smile:
